### ISSUE TITLE
View their default-set consultation slots on calender (Lecturer)

### ISSUE THREAD

**Issue by 2351852** [witseie-elen4010/2023-group-lab-007#20]
## Description
- View the calendar with dummy consultations on the lecturer dashboard.

**Comment by Gilad-Kangisser** [comment]
## Acceptance criteria
### Lecturer Dashboard
- User can view the lecturer dashboard.
- User can see the calendar of the current month.
- User can view different months on the calendar.
- User can press a button to show dummy consultations.
